### ISSUE TITLE
Modal verification not displaying on "Verify Me" click

### ISSUE THREAD

**Issue by Matt-Copenhaver** [bz-stripe/identity-verification-sample#16]
Running the sample on node, the modal verification is not displaying when I click "Verify Me."

Stripe creates a new Verification Session on the click, which I can see in the dashboard.

Browser console returns:

```
index.js:39 Error: TypeError: Cannot read property 'trim' of undefined
    at (index):1
    at Ks ((index):1)
    at nu.<anonymous> ((index):1)
    at nu.verifyIdentity ((index):1)
    at index.js:28
```

Node returns no messages in Terminal.

Using the "Open verification session in a new tab" link works.

![Screen Shot 2021-03-23 at 5 19 34 PM](https://user-images.githubusercontent.com/63939427/112337797-d8277100-8c83-11eb-9096-58a8e77de521.png)

**Comment by bz-stripe** [comment]
It looks like we could show a much better error message in this case.

But I'm struggling to reproduce this. Did you change any of the code on the server-side?

**Comment by bz-stripe** [comment]
Ah, I do have a potential repro — if the `use_stripe_sdk` parameter is not included in the create VerificationSession API call on the server.

For example, if this line is deleted or set to `false`: https://github.com/bz-stripe/identity-verification-sample/blob/master/without-webhooks/server/server.js#L99

**Comment by Matt-Copenhaver** [comment]
Yes - the error preceding this one was 'unknown parameter: use_stripe_sdk'
The code I was trying to run locally commented that out, which solved that problem, but created another one...  oops.
Struggling to recreate the 'unknown parameter' error now.

Uncommented use_stripe_sdk, and all is working well now - on both the using-webhooks and without-webhooks branches.

**Comment by bz-stripe** [comment]
Ah yeah, sorry about that. There was a permission configuration error earlier. But it should be fixed now.
