### ISSUE TITLE
.env instruction - path

### ISSUE THREAD

**Issue by ravenOSS** [bz-stripe/identity-verification-sample#8]
Correct path to client in the server .env file should be preceded by double dot?

**Comment by bz-stripe** [comment]
Actually, I think dotenv looks in the project root directory: https://github.com/motdotla/dotenv#usage.

Do you get an error when you put the .env file next to env.example?

**Comment by ravenOSS** [comment]
I'll have to take another look. 
Normally I would have a root .env but the instructions are to copy env.example to the server directory as .env Therefore, path to client would be incorrect. No?

**Comment by bz-stripe** [comment]
@ravenOSS thanks for pointing out the docs were outdated! I updated that step 😄
